version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Oefening
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:



